003.myblog.FILES/myblog/app_blog/urls.py
from django.urls import path
from myblog.views import MainView
from app_blog.views import (
    posts_list,
    create_post,
    PostDetailsView,
    upload_post,
    PostDeleteView,
    PostUpdateView,
)


app_name = "app_blog"

urlpatterns = [
    path('', MainView.as_view(), name='main'),
    path('posts_list/', posts_list, name='posts_list'),
    path('create_post/', create_post, name='create_post'),
    path('upload_post/', upload_post, name='upload_post'),
    path('posts_list/post_<int:pk>', PostDetailsView.as_view(), name='post_detail'),
    path('posts_list/post_<int:pk>/post_update', PostUpdateView.as_view(), name='post_update'),
    path('posts_list/post_<int:pk>/confirm-delete', PostDeleteView.as_view(), name='post_delete'),
]

003.myblog.FILES/myblog/myblog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from myblog.views import MainView, UserLoginView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainView.as_view(), name='main'),
    path('', UserLoginView.as_view(), name='login'),
    path('users/', include('app_users.urls')),
    path('blog/', include('app_blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

003.myblog.FILES/myblog/app_blog/models.py
import os

from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


def user_directory_path(instance, filename):
    return 'images/post_{0}/{1}'.format(instance.pk, filename)


# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Author')
    title = models.CharField(max_length=30, verbose_name='Title')
    content = models.TextField(verbose_name='Content')
    created_at = models.DateTimeField(default=timezone.now, verbose_name='Created date')
    images = models.ImageField(upload_to=user_directory_path, verbose_name='Images (model)', null=True, blank=True)

    def images_path(self):
        img_path = []
        if os.path.exists(os.path.abspath(f'upload/images/post_{self.pk}')):
            for image in os.listdir(os.path.abspath(f'upload/images/post_{self.pk}')):
                img_path.append(os.path.join(f'/upload/images/post_{self.pk}/{image}'))
        return img_path


class File(models.Model):
    file = models.FileField(upload_to='files/', verbose_name='Post(s) for upload')

003.myblog.FILES/myblog/app_blog/forms.py
from django import forms

from app_blog.models import Post


class PostForm(forms.ModelForm):
    images_field = forms.ImageField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

    class Meta:
        model = Post
        fields = ['title', 'content', 'images_field']


class UploadPostForm(forms.Form):
    file = forms.FileField(help_text='Post(s) for upload')

003.myblog.FILES/myblog/app_blog/views.py
from csv import reader

from app_blog.models import Post, File
from app_blog.forms import PostForm, UploadPostForm

from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.files.base import ContentFile
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, reverse, redirect
from django.urls import reverse_lazy
from django.views.generic import DetailView, DeleteView, UpdateView


def posts_list(request):
    posts_list = Post.objects.order_by('-created_at')
    return render(request, 'app_blog/posts_list.html', {'posts_list': posts_list})


@login_required
@permission_required('app_blog.add_post')
def create_post(request: HttpRequest) -> HttpResponse:
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            user = request.user
            title = form.cleaned_data['title']
            content = form.cleaned_data['content']
            images = request.FILES.getlist('images_field')
            post = Post.objects.create(user=user, title=title, content=content)
            for img in images:
                data = img.read()
                post.images.save(img.name, ContentFile(data))
                post.save()
            url = reverse('app_blog:posts_list')
            return redirect(url)
    else:
        form = PostForm()
    context = {
        "form": form
    }
    return render(request, 'app_blog/post_form.html', context=context)


@login_required
@permission_required('app_blog.add_post')
def upload_post(request):
    if request.method == 'POST':
        form = UploadPostForm(request.POST, request.FILES)
        if form.is_valid():
            post_file = form.cleaned_data['file'].read()
            post_str = post_file.decode("utf-8").split('\n')
            if post_str[-1] == '':
                post_str = post_str[:-1]
                csv_reader = reader(post_str, delimiter=";", quotechar='"')
            else:
                csv_reader = reader(post_str, delimiter=":", quotechar='"')
            for row in csv_reader:
                Post.objects.create(
                    user=request.user,
                    title=row[0],
                    content=row[1]
                )
            url = reverse('app_blog:posts_list')
            return redirect(url)
    else:
        form = UploadPostForm()
    context = {"form": form}
    return render(request, 'app_blog/upload_post.html', context=context)


class PostDetailsView(DetailView):
    template_name = 'app_blog/post_detail.html'
    model = Post
    context_object_name = "post"


class PostDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = 'app_blog.delete_post'
    model = Post
    success_url = reverse_lazy("app_blog:posts_list")


class PostUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'app_blog.change_post'
    model = Post
    fields = "title", "content", "images"
    template_name_suffix = "_update_form"

    def get_success_url(self):
        return reverse("app_blog:post_detail", kwargs={"pk": self.object.pk},)

003.myblog.FILES/myblog/app_blog/templates/app_blog/post_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Confirm delete post #{{ object.pk }}</title>
</head>
<body>
  <h1>Are you sure want to delete post #{{ object.pk }}?</h1>
  <br>
  <div>
    <a href="{% url 'app_blog:post_detail' pk=object.pk %}">Back to post</a>
  </div>
  <br>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Delete</button>
    </form>
  </div>
</body>
</html>

003.myblog.FILES/myblog/app_blog/templates/app_blog/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Post {{ post.pk }} details</title>
</head>
<body>
    <h1>Post {{ post.pk }} details</h1>
    <p>Author: {% firstof post.user.profile.name post.user.username %}</p>
    <p>Title: {{ post.title }}</p>
    <p>Content: {{ post.content }}</p>
    <p>Date of created: {{ post.created_at }}</p>
    {% if post.images_path %}
        {% for img_path in post.images_path %}
            <img src="{{ img_path }}">
        {% endfor %}
    {% endif %}
    <br>
    <p><a href="{% url 'app_blog:post_update' pk=post.pk %}">Update post</a></p>
    <br>
    <p><a href="{% url 'app_blog:post_delete' pk=post.pk %}">Delete post</a></p>
    <br>
    <p><a href="{% url 'app_blog:posts_list' %}">Back to posts list</a></p>
    <p><a href="{% url 'main' %}">Back to main</a></p>
</body>
</html>

003.myblog.FILES/myblog/app_blog/templates/app_blog/post_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create post</title>
</head>
<body>
  <h1>Create post</h1>
  <div>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Create</button>
    </form>
  </div>
  <div>
    <a href="{% url 'app_blog:posts_list' %}">Back to posts list</a>
  </div>
</body>
</html>

003.myblog.FILES/myblog/app_blog/templates/app_blog/post_update_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Update post</title>
</head>
<body>
    <h1>Update post</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit">Update</button>
        </form>
    </div>
    <div>
    <a href="{% url 'app_blog:post_detail' pk=object.pk %}">Back to post</a>
    </div>
</body>
</html>

003.myblog.FILES/myblog/app_blog/templates/app_blog/posts_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Posts list</title>
</head>
<body>
    <h1>Posts list</h1>
    {% for post in posts_list %}
        <div>
            <p><strong>Author: {% firstof post.user.profile.name post.user.username %}</strong></p>
            <p>{{ post.content|truncatechars:100 }}</p>
            <p>{{ post.created_at }}</p>
            <p><a href="{% url 'app_blog:post_detail' pk=post.pk %}"><small>more details...</small></a></p>
            <p>---------------------------------------</p>
        </div>
    {% endfor %}
    {% if not posts_list %}
        <h2>No posts yet.</h2>
        <br>
    {% endif %}
    <p><a href="{% url 'app_blog:create_post' %}">Create post</a></p>
    <p><a href="{% url 'app_blog:upload_post' %}">Upload post(s)</a></p>
    <p><a href="{% url 'main' %}">Back to main</a></p>
</body>
</html>

003.myblog.FILES/myblog/app_blog/templates/app_blog/upload_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Upload post(s)</title>
</head>
<body>
  <h1>Upload post(s)</h1>
  <div>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Upload file</button>
    </form>
  </div>
  <p><a href="{% url 'app_blog:posts_list' %}">Back to posts list</a></p>

</body>
</html>