001.app_shop-app_users.CBS.AUTH/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite.views import MainView


urlpatterns = [
    path('', MainView.as_view(), name='main'),
    path('admin/', admin.site.urls),
    path('shop/', include('shopapp.urls')),
    path('users/', include('app_users.urls')),
]

001.app_shop-app_users.CBS.AUTH/mysite/shopapp/urls.py
from django.urls import path
from mysite.views import MainView
from .views import (
    ShopIndexView,
    GroupsListView,
    ProductDetailsView,
    ProductsListView,
    OrdersListView,
    OrdersDetailView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    OrderCreateView,
    OrderUpdateView,
    OrderDeleteView,
    CommentsListView,
    CommentDetailView,
    # CommentCreateView,
    CommentUpdateView,
    CommentDeleteView,
    create_comment,
)

app_name = "shopapp"

urlpatterns = [
    path('', MainView.as_view(), name='main'),
    path("index/", ShopIndexView.as_view(), name="index"),
    path("groups/", GroupsListView.as_view(), name="groups_list"),
    path("products/", ProductsListView.as_view(), name="products_list"),
    path("products/create/", ProductCreateView.as_view(), name="product_create"),
    path("products/<int:pk>", ProductDetailsView.as_view(), name="product_details"),
    path("products/<int:pk>/update", ProductUpdateView.as_view(), name="product_update"),
    path("products/<int:pk>/confirm-delete", ProductDeleteView.as_view(), name="product_delete"),
    path("orders/", OrdersListView.as_view(), name="orders_list"),
    path("orders/<int:pk>", OrdersDetailView.as_view(), name="order_details"),
    path("orders/create/", OrderCreateView.as_view(), name="order_create"),
    path("orders/<int:pk>/update", OrderUpdateView.as_view(), name="order_update"),
    path("orders/<int:pk>/confirm-delete", OrderDeleteView.as_view(), name="order_delete"),
    path("comments/", CommentsListView.as_view(), name="comments_list"),
    path("comments/<int:pk>", CommentDetailView.as_view(), name="comment_details"),
    # path("comments/create/", CommentCreateView.as_view(), name="comment_create"),
    path("comments/create/", create_comment, name="comment_create"),
    path("comments/<int:pk>/update", CommentUpdateView.as_view(), name="comment_update"),
    path("comments/<int:pk>/confirm-delete", CommentDeleteView.as_view(), name="comment_delete"),
]

001.app_shop-app_users.CBS.AUTH/mysite/shopapp/models.py
from django.contrib.auth.models import User
from django.db import models


class Product(models.Model):
    class Meta:
        ordering = ["name", "price"]

    name = models.CharField(max_length=100)
    description = models.TextField(null=False, blank=True)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    discount = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)

    def __str__(self):
        return f"Product(pk={self.pk}, name={self.name!r})"


class Order(models.Model):
    delivery_address = models.TextField(null=True, blank=True)
    promocode = models.CharField(max_length=20, null=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name="orders")


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    name = models.CharField(default='anonim', max_length=100)
    comment_text = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

001.app_shop-app_users.CBS.AUTH/mysite/shopapp/forms.py
from django.contrib.auth.models import Group
from django.forms import ModelForm
from .models import Comment


class GroupForm(ModelForm):
    class Meta:
        model = Group
        fields = ["name"]


class Comment1Form(ModelForm):
    class Meta:
        model = Comment
        fields = ["comment_text"]


class Comment2Form(ModelForm):
    class Meta:
        model = Comment
        fields = ["name", "comment_text"]

001.app_shop-app_users.CBS.AUTH/mysite/shopapp/views.py
from timeit import default_timer

from django.contrib.auth.models import Group, User
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView

from .forms import GroupForm, Comment1Form, Comment2Form
from .models import Product, Order, Comment


class ShopIndexView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        products = [
            ('Laptop', 1999),
            ('Desktop', 2999),
            ('Smartphone', 999),
        ]
        context = {
            "time_running": default_timer(),
            "products": products,
        }
        return render(request, 'shopapp/shop-index.html', context=context)


class GroupsListView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        context = {
            "form": GroupForm(),
            "groups": Group.objects.prefetch_related('permissions').all(),
        }
        return render(request, 'shopapp/groups-list.html', context=context)

    def post(self, request: HttpRequest):
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()

        return redirect(request.path)


# class ProductDetailsView(View):
#     def get(self, request: HttpRequest, pk: int) -> HttpResponse:
#         product = get_object_or_404(Product, pk=pk)
#         context = {
#             "product": product,
#         }
#         return render(request, "shopapp/product-details.html", context=context)


class ProductDetailsView(DetailView):
    template_name = "shopapp/product-details.html"
    model = Product
    context_object_name = "product"


# class ProductsListView(TemplateView):
#     template_name = "shopapp/products-list.html"
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context["products"] = Product.objects.all()
#         return context


class ProductsListView(ListView):
    template_name = "shopapp/products-list.html"
    # model = Product
    context_object_name = "products"
    queryset = Product.objects.filter(archived=False)


class ProductCreateView(CreateView):
    model = Product
    fields = "name", "price", "description", "discount"
    # form_class = ProductForm # через Форму или ч/з поля
    success_url = reverse_lazy("shopapp:products_list")


class ProductUpdateView(UpdateView):
    model = Product
    fields = "name", "price", "description", "discount"
    template_name_suffix = "_update_form"

    def get_success_url(self):
        return reverse("shopapp:product_details", kwargs={"pk": self.object.pk},)


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy("shopapp:products_list")

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)


# def orders_list(request: HttpRequest):
#     context = {
#         "orders": Order.objects.select_related("user").prefetch_related("products").all(),
#     }
#     return render(request, 'shopapp/order_list.html', context=context)


class OrdersListView(ListView):
    queryset = (
        Order.objects.select_related("user").prefetch_related("products")
    )


class OrdersDetailView(DetailView):
    queryset = (
        Order.objects.select_related("user").prefetch_related("products")
    )


class OrderCreateView(CreateView):
    model = Order
    fields = "delivery_address", "promocode", "user", "products"
    # form_class = OrderForm # через Форму или ч/з поля
    success_url = reverse_lazy("shopapp:orders_list")


class OrderUpdateView(UpdateView):
    model = Order
    fields = "delivery_address", "promocode", "user", "products"
    template_name_suffix = "_update_form"

    def get_success_url(self):
        return reverse("shopapp:order_details", kwargs={"pk": self.object.pk},)


class OrderDeleteView(DeleteView):
    model = Order
    success_url = reverse_lazy("shopapp:orders_list")


class CommentsListView(ListView):
    template_name = "shopapp/comment_list.html"
    model = Comment
    context_object_name = "comments"


class CommentDetailView(DetailView):
    template_name = "shopapp/comment_detail.html"
    model = Comment
    context_object_name = "comment"


# class CommentCreateView(CreateView):
#     model = Comment
#     fields = "user", "comment_text"
#     success_url = reverse_lazy("shopapp:comments_list")


def create_comment(request: HttpRequest) -> HttpResponse:
    if request.method == 'POST':
        if request.user.is_authenticated:
            form = Comment1Form(request.POST)
            if form.is_valid():
                comment_text = form.cleaned_data['comment_text']
                user = request.user
                name = request.user.first_name
                Comment.objects.create(user=user, name=name, comment_text=comment_text)
                url = reverse('shopapp:comments_list')
                return redirect(url)
        else:
            form = Comment2Form(request.POST)
            if form.is_valid():
                comment_text = form.cleaned_data['comment_text']
                user = User.objects.get(username="guest")
                name = form.cleaned_data['name']
                Comment.objects.create(user=user, name=name, comment_text=comment_text)
                url = reverse('shopapp:comments_list')
                return redirect(url)
    else:
        if request.user.is_authenticated:
            form = Comment1Form()
        else:
            form = Comment2Form()
    context = {
        "form": form
    }
    return render(request, 'shopapp/comment_form.html', context=context)


class CommentUpdateView(UpdateView):
    model = Comment
    fields = "name", "comment_text"
    template_name_suffix = "_update_form"

    def get_success_url(self):
        return reverse("shopapp:comment_details", kwargs={"pk": self.object.pk},)


class CommentDeleteView(DeleteView):
    model = Comment
    success_url = reverse_lazy("shopapp:comments_list")

001.app_shop-app_users.CBS.AUTH/mysite/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>
    {% block title %}
      Base Title
    {% endblock %}
  </title>
</head>
<body>

{% block body %}
  Base body
{% endblock %}

</body>
</html>

001.app_shop-app_users.CBS.AUTH/mysite/shopapp/templates/shopapp/comment_confirm_delete.html
{% extends 'shopapp/base.html' %}


{% block title %}
  Confirm delete comment #{{ object.pk }}
{% endblock %}

{% block body %}
  <h1>Are you sure want to delete comment #{{ object.pk }}?</h1>
  <br>
  <div>
    <a href="{% url 'shopapp:comment_details' pk=object.pk %}">Back to comment</a>
  </div>
  <br>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Delete</button>
    </form>
  </div>
{% endblock %}

001.app_shop-app_users.CBS.AUTH/mysite/shopapp/templates/shopapp/comment_detail.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Comment #{{ object.pk }} details
{% endblock %}

{% block body %}
  <h1>Comment # {{ object.pk }}</h1>
  <div>
    <p>Comment by {% firstof object.user.first_name object.user.username %}</p>
    <p>Comment text: {{ comment.comment_text }}</p>
    <p>Comment data: {{ comment.created_at }}</p>
  </div>
  <div>
    <a href="{% url 'shopapp:comment_update' pk=comment.pk %}">Update comment</a>
  </div>
  <div>
    <a href="{% url 'shopapp:comment_delete' pk=comment.pk %}">Delete comment</a>
  </div>
  <div>
    <a href="{% url 'shopapp:comments_list' %}">Back to comments list</a>
  </div>
{% endblock %}

001.app_shop-app_users.CBS.AUTH/mysite/shopapp/templates/shopapp/comment_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Create comment
{% endblock %}

{% block body %}
  <h1>Create comment</h1>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Create</button>
    </form>
  </div>
  <div>
    <a href="{% url 'shopapp:comments_list' %}">Back to comments list</a>
  </div>
{% endblock %}

001.app_shop-app_users.CBS.AUTH/mysite/shopapp/templates/shopapp/comment_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Comments list
{% endblock %}

{% block body %}
  <h1>Comments:</h1>
  {% if comments %}
    <div>
      {% for comment in comments %}
        <div>
          <p><a href="{% url 'shopapp:comment_details' pk=comment.pk %}">Details of comment #{{ comment.pk }}</a></p>
          {% if comment.user.username != 'guest' %}
            <p>Comment by {% firstof comment.user.first_name comment.user.username %}</p>
          {% else %}
            <p>Comment by guest(anonim) - {{ comment.name }}</p>
          {% endif %}
          <p>Comment text: {{ comment.comment_text }}</p>
        </div>
      {% endfor %}
    </div>
  {% else %}
    <h3>No comments yet</h3>
  {% endif %}

  <div>
    <a href="{% url 'shopapp:comment_create' %}">Create a new comment</a>
  </div>

  <br>
  <div>
    <a href="{% url 'main' %}">Back to main</a>
  </div>
{% endblock %}

001.app_shop-app_users.CBS.AUTH/mysite/shopapp/templates/shopapp/comment_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Update comment
{% endblock %}

{% block body %}
  <h1>Update comment</h1>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Update</button>
    </form>
  </div>
  <div>
    <a href="{% url 'shopapp:comment_details' pk=object.pk %}">Back to comment</a>
  </div>
{% endblock %}

001.app_shop-app_users.CBS.AUTH/mysite/shopapp/templates/shopapp/order_confirm_delete.html
{% extends 'shopapp/base.html' %}


{% block title %}
  Confirm delete order #{{ object.pk }}
{% endblock %}

{% block body %}
  <h1>Are you sure want to delete order #{{ object.pk }}?</h1>
  <br>
  <div>
    <a href="{% url 'shopapp:order_details' pk=object.pk %}">Back to order</a>
  </div>
  <br>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Delete</button>
    </form>
  </div>
{% endblock %}

001.app_shop-app_users.CBS.AUTH/mysite/shopapp/templates/shopapp/order_detail.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Order #{{ object.pk }} details
{% endblock %}

{% block body %}
  <h1>Order # {{ object.pk }}</h1>
  <div>
    <p>Order by {% firstof object.user.first_name object.user.username %}</p>
    <p>Promocode: <code>{{ object.promocode }}</code></p>
    <p>Delivery address: {{ object.delivery_address }}</p>
    <div>
      Product in order:
      <ul>
        {% for product in object.products.all %}
          <li>{{ product.name }} for ${{ product.price }}</li>
        {% endfor %}

      </ul>
    </div>
  </div>
  <div>
    <a href="{% url 'shopapp:order_update' pk=order.pk %}">Update order</a>
  </div>
  <div>
    <a href="{% url 'shopapp:order_delete' pk=order.pk %}">Delete order</a>
  </div>
  <div>
    <a href="{% url 'shopapp:orders_list' %}">Back to orders list</a>
  </div>
{% endblock %}

001.app_shop-app_users.CBS.AUTH/mysite/shopapp/templates/shopapp/order_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Create order
{% endblock %}

{% block body %}
  <h1>Create order</h1>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Create</button>
    </form>
  </div>
  <div>
    <a href="{% url 'shopapp:orders_list' %}">Back to orders list</a>
  </div>
{% endblock %}

001.app_shop-app_users.CBS.AUTH/mysite/shopapp/templates/shopapp/order_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Update order
{% endblock %}

{% block body %}
  <h1>Update order</h1>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Update</button>
    </form>
  </div>
  <div>
    <a href="{% url 'shopapp:order_details' pk=object.pk %}">Back to order</a>
  </div>
{% endblock %}

001.app_shop-app_users.CBS.AUTH/mysite/shopapp/templates/shopapp/product-details.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Product #{{ product.pk }}
{% endblock %}

{% block body %}
  <h1>Product <strong>{{ product.name }}</strong></h1>
  <div>
    <div>Description: <em>{{ product.description }}</em></div>
    <div>Price: {{ product.price }}</div>
    <div>Discount: {{ product.discount }}</div>
    <div>Archived: {{ product.archived }}</div>
  </div>
  <div>
    <a href="{% url 'shopapp:product_update' pk=product.pk %}">Update product</a>
  </div>
  <div>
    <a href="{% url 'shopapp:product_delete' pk=product.pk %}">Delete product</a>
  </div>
  <div>
    <a href="{% url 'shopapp:products_list' %}">Back to products list</a>
  </div>
{% endblock %}

001.app_shop-app_users.CBS.AUTH/mysite/shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}


{% block title %}
  Confirm delete {{ object.name }}
{% endblock %}

{% block body %}
  <h1>Are you sure want to delete {{ object.name }}?</h1>
  <br>
  <div>
    <a href="{% url 'shopapp:product_details' pk=object.pk %}">Back to product</a>
  </div>
  <br>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Delete</button>
    </form>
  </div>
{% endblock %}

001.app_shop-app_users.CBS.AUTH/mysite/shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Create product
{% endblock %}

{% block body %}
  <h1>Create product</h1>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Create</button>
    </form>
  </div>
  <div>
    <a href="{% url 'shopapp:products_list' %}">Back to products list</a>
  </div>
{% endblock %}

001.app_shop-app_users.CBS.AUTH/mysite/shopapp/templates/shopapp/products-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Products list
{% endblock %}

{% block body %}
  <h1>Products:</h1>
  {% if products %}
    <div>
    {% for product in products %}
      <div>
        <p><a href="{% url 'shopapp:product_details' pk=product.pk %}">Name: {{ product.name }}</a></p>
        <p>Price: {{ product.price }}</p>
        <p>Discount: {% firstof product.discount 'no discount' %}</p>
      </div>
    {% endfor %}

    </div>

  {% else %}
    <h3>No products yet</h3>
  {% endif %}
  <div>
    <a href="{% url 'shopapp:product_create' %}">Create a new product</a>
  </div>
  <br>
  <div>
    <a href="{% url 'main' %}">Back to main</a>
  </div>
{% endblock %}