001.app_shop-app_users.CBS.AUTH/mysite/app_users/urls.py
from django.urls import path
from app_users.views import AnotherLoginView, AnotherLogoutView
from mysite.views import MainView


urlpatterns = [
    path('', MainView.as_view(), name='main'),
    path('login/', AnotherLoginView.as_view(), name='login'),
    path('logout/', AnotherLogoutView.as_view(), name='logout'),
]

001.app_shop-app_users.CBS.AUTH/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite.views import MainView


urlpatterns = [
    path('', MainView.as_view(), name='main'),
    path('admin/', admin.site.urls),
    path('shop/', include('shopapp.urls')),
    path('users/', include('app_users.urls')),
]

001.app_shop-app_users.CBS.AUTH/mysite/shopapp/urls.py
from django.urls import path
from mysite.views import MainView
from .views import (
    ShopIndexView,
    GroupsListView,
    ProductDetailsView,
    ProductsListView,
    OrdersListView,
    OrdersDetailView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    OrderCreateView,
    OrderUpdateView,
    OrderDeleteView,
    CommentsListView,
    CommentDetailView,
    # CommentCreateView,
    CommentUpdateView,
    CommentDeleteView,
    create_comment,
)

app_name = "shopapp"

urlpatterns = [
    path('', MainView.as_view(), name='main'),
    path("index/", ShopIndexView.as_view(), name="index"),
    path("groups/", GroupsListView.as_view(), name="groups_list"),
    path("products/", ProductsListView.as_view(), name="products_list"),
    path("products/create/", ProductCreateView.as_view(), name="product_create"),
    path("products/<int:pk>", ProductDetailsView.as_view(), name="product_details"),
    path("products/<int:pk>/update", ProductUpdateView.as_view(), name="product_update"),
    path("products/<int:pk>/confirm-delete", ProductDeleteView.as_view(), name="product_delete"),
    path("orders/", OrdersListView.as_view(), name="orders_list"),
    path("orders/<int:pk>", OrdersDetailView.as_view(), name="order_details"),
    path("orders/create/", OrderCreateView.as_view(), name="order_create"),
    path("orders/<int:pk>/update", OrderUpdateView.as_view(), name="order_update"),
    path("orders/<int:pk>/confirm-delete", OrderDeleteView.as_view(), name="order_delete"),
    path("comments/", CommentsListView.as_view(), name="comments_list"),
    path("comments/<int:pk>", CommentDetailView.as_view(), name="comment_details"),
    # path("comments/create/", CommentCreateView.as_view(), name="comment_create"),
    path("comments/create/", create_comment, name="comment_create"),
    path("comments/<int:pk>/update", CommentUpdateView.as_view(), name="comment_update"),
    path("comments/<int:pk>/confirm-delete", CommentDeleteView.as_view(), name="comment_delete"),
]

001.app_shop-app_users.CBS.AUTH/mysite/app_users/models.py
from django.db import models

# Create your models here.

001.app_shop-app_users.CBS.AUTH/mysite/app_users/forms.py
from django import forms


class AuthForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

001.app_shop-app_users.CBS.AUTH/mysite/app_users/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpRequest
from django.shortcuts import render
from app_users.forms import AuthForm
from django.contrib.auth.views import LoginView, LogoutView

import datetime


class AnotherLoginView(LoginView):
    template_name = 'app_users/login.html'


class AnotherLogoutView(LogoutView):
    # template_name = 'users/logout.html'
    next_page = '/'

001.app_shop-app_users.CBS.AUTH/mysite/app_users/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Главная страница</title>
</head>
<body>
  <h1>Я - гланая страница</h1>
  <br>
  {% if request.user.is_authenticated %}
    <h3>Добро пожаловать на сайт {{ request.user.username }}</h3>

    <br>
    <div>
      <a href="{% url 'logout' %}">Выйти</a>
    </div>
  {% else %}
    <h3>Вы неавторизированны на нашем сайте.</h3>
    <div>
      <a href="{% url 'login' %}">Войти</a>
    </div>
  {% endif %}
    <br>
    <h2>Меню сайта</h2>
    <div>
    <a href="{% url 'shopapp:groups_list' %}">Groups</a>
    </div>
    <br>
    <div>
    <a href="{% url 'shopapp:index' %}">Shop Index</a> <!-- shop/ -->
    </div>
    <br>
    <div>
    <a href="{% url 'shopapp:products_list' %}">Products list</a>
    </div>
    <br>
    <div>
    <a href="{% url 'shopapp:orders_list' %}">Orders list</a>
    </div>
    <br>
    <div>
    <a href="{% url 'shopapp:comments_list' %}">Comments list</a>
    </div>
</body>
</html>