002.app_news.REG.PERM/mysite/app_news/urls.py
from django.urls import path
from mysite.views import MainView
from .views import (
    news_list,
    news_list_moder,
    # NewsDetailsView,
    news_details,
    NewsDetailsModerView,
    # moder_news,
    # NewsCreateView,
    create_news,
    NewsUpdateView,
    NewsDeleteView,
    # EArticleView,
    # add_comment,
)

app_name = "app_news"

urlpatterns = [
    path('', MainView.as_view(), name='main'),
    path('news_list/', news_list, name='news_list'),
    path('news_list_moder/', news_list_moder, name='news_list_moder'),
    # path("news_list/<int:pk>", NewsDetailsView.as_view(), name="news_details"),
    path("news_list/<int:pk>", news_details, name="news_details"),
    path("news_list_moder/<int:pk>", NewsDetailsModerView.as_view(), name="news_details_moder"),
    # path("news_list_moder/<int:pk>", moder_news, name="news_details_moder"),
    # path("news_list/create/", NewsCreateView.as_view(), name="news_create"),
    path("news_list/create/", create_news, name="news_create"),
    path("news_list/<int:pk>/update", NewsUpdateView.as_view(), name="news_update"),
    path("news_list/<int:pk>/confirm-delete", NewsDeleteView.as_view(), name="news_delete"),
]

002.app_news.REG.PERM/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite.views import MainView


urlpatterns = [
    path('', MainView.as_view(), name='main'),
    path('admin/', admin.site.urls),
    path('users/', include('app_users.urls')),
    path('news/', include('app_news.urls')),
]

002.app_news.REG.PERM/mysite/app_news/models.py
from django.db import models
from django.contrib.auth.models import User
# from django.contrib.postgres.fields import ArrayField
from django.utils import timezone


class News(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, verbose_name='Пользователь')
    title = models.CharField(max_length=30, verbose_name='Заголовок')
    content = models.TextField(verbose_name='Текст новости')
    publisher = models.CharField(max_length=30, verbose_name='Кто опубликовал')
    created_at = models.DateTimeField(verbose_name='Дата создания', default=timezone.now)
    is_active = models.BooleanField(verbose_name='Активность', default=False)


    class Meta:
        verbose_name = 'новость'
        verbose_name_plural = 'новости'
        permissions = {
            ("can_verify", "Может проверить"),
        }

    def __str__(self):
        return self.title


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Пользователь')
    news = models.ForeignKey(News, on_delete=models.CASCADE, verbose_name='Какой новости')
    name = models.CharField(default='anonim', max_length=100, verbose_name='Автор')
    comment_text = models.TextField(null=True, blank=True, verbose_name='Комментарий')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    def __str__(self):
        return self.comment_text

002.app_news.REG.PERM/mysite/app_news/forms.py
from django.contrib.auth.models import Group
from django.forms import ModelForm
from .models import News, Comment
from django import forms


class NewsForm(ModelForm):
    class Meta:
        model = News
        fields = ["title", "content", "publisher"]
        exclude = ["author", "created_at", "is_active"]


class Comment1Form(ModelForm):
    class Meta:
        model = Comment
        fields = ["comment_text"]


class Comment2Form(ModelForm):
    class Meta:
        model = Comment
        fields = ["name", "comment_text"]

002.app_news.REG.PERM/mysite/app_news/views.py
from django.contrib.auth.models import Group, User
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect, Http404
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import permission_required, login_required
from django.contrib.auth.mixins import PermissionRequiredMixin

from app_news.forms import NewsForm, Comment1Form, Comment2Form
from app_news.models import News, Comment
from app_users.models import Profile


# @permission_required('app_news.view_news')
def news_list(request):
    filter_for_list = 'created_at'
    if request.method == 'POST':
        filter_for_list = request.POST['format']
    news = News.objects.order_by(filter_for_list)
    return render(request, 'app_news/news_list.html', {'news_list': news})


@permission_required('app_news.change_news')
def news_list_moder(request):
    news = News.objects.all()
    return render(request, 'app_news/news_list_moder.html', {'news_list': news})


# class NewsDetailsView(DetailView):
#     template_name = "app_news/news_detail.html"
#     model = News
#     context_object_name = "news"


def news_details(request: HttpRequest, pk) -> HttpResponse:
    if request.method == 'POST':
        news = News.objects.get(pk=pk)
        if request.user.is_authenticated:
            form = Comment1Form(request.POST)
            if form.is_valid():
                user = request.user
                name = request.user.first_name
                news = news
                comment_text = form.cleaned_data['comment_text']
                Comment.objects.create(user=user, name=name, news=news, comment_text=comment_text)
                url = reverse('app_news:news_details', kwargs={"pk": pk})
                return redirect(url)
        else:
            form = Comment2Form(request.POST)
            if form.is_valid():
                # user,_ = User.objects.get_or_create(username="guest")
                news = news
                name = form.cleaned_data['name']
                comment_text = form.cleaned_data['comment_text']
                Comment.objects.create(name=name, news=news, comment_text=comment_text)
                url = reverse('app_news:news_details', kwargs={"pk": pk})
                return redirect(url)
    else:
        news = News.objects.get(pk=pk)
        if request.user.is_authenticated:
            form = Comment1Form()
        else:
            form = Comment2Form()
    context = {
        'form': form,
        'comments': Comment.objects.filter(news=news),
        'news': news,
    }
    return render(request, 'app_news/news_detail.html', context=context)


@login_required
@permission_required('app_news.add_news')
def create_news(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = NewsForm(request.POST)
        if form.is_valid():
            num_news = request.user.profile.num_news + 1
            Profile.objects.filter(user=request.user).update(
                num_news=num_news
            )
            author = request.user
            title = form.cleaned_data['title']
            content = form.cleaned_data['content']
            publisher = form.cleaned_data['publisher']
            News.objects.create(author=author, title=title, content=content, publisher=publisher)
            # form.save()
            url = reverse('app_news:news_list')
            return redirect(url)
    else:
        form = NewsForm()
    context = {
        "form": form
    }
    return render(request, 'app_news/news_form.html', context=context)


# class NewsCreateView(PermissionRequiredMixin, CreateView):
#     permission_required = 'app_news.add_news'
#     model = News
#     fields = "title", "content", "publisher"
#     success_url = reverse_lazy("news_list")


class NewsUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'app_news.change_news'
    model = News
    fields = "title", "content", "publisher"
    template_name_suffix = "_update_form"

    def get_success_url(self):
        return reverse("app_news:news_details", kwargs={"pk": self.object.pk},)


class NewsDetailsModerView(PermissionRequiredMixin, UpdateView):
    permission_required = 'app_news.change_news'
    model = News
    fields = "title", "content", "publisher", "is_active"
    template_name_suffix = "_detail_moder"

    def get_success_url(self):
        return reverse("app_news:news_details", kwargs={"pk": self.object.pk},)


class NewsDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = 'app_news.delete_news'
    model = News
    success_url = reverse_lazy("app_news:news_list")

    # def update_num_news(self, request: HttpRequest):
    #     num_news = request.user.profile.num_news - 1
    #     Profile.objects.filter(user=request.user).update(
    #         num_news=num_news
    #     )


# class EArticleView(View):
#     template_name = 'app_news/news_detail.html'
#     comment_form = CommentForm
#
#     def get(self, request, *args, **kwargs):
#         news = get_object_or_404(News, id=self.kwargs['article_id'])
#         context = {}
#         context.update(csrf(request))
#         user = auth.get_user(request)
#         # Помещаем в контекст все комментарии, которые относятся к статье
#         # попутно сортируя их по пути, ID автоинкрементируемые, поэтому
#         # проблем с иерархией комментариев не должно возникать
#         context['comments'] = news.comment_set.all().order_by('path')
#         context['next'] = news.get_absolute_url()
#         # Будем добавлять форму только в том случае, если пользователь авторизован
#         if user.is_authenticated:
#             context['form'] = self.comment_form
#
#         return render_to_response(template_name=self.template_name, context=context)
#
#
# # Декораторы по которым, только авторизованный пользователь
# # может отправить комментарий и только с помощью POST запроса
# @login_required
# @require_http_methods(["POST"])
#
# def add_comment(request, article_id):
#
#     form = CommentForm(request.POST)
#     news = get_object_or_404(News, id=article_id)
#
#     if form.is_valid():
#         comment = CommentV2()
#         comment.path = []
#         comment.article_id = news
#         comment.author_id = auth.get_user(request)
#         comment.content = form.cleaned_data['comment_area']
#         comment.save()
#
#         # Django не позволяет увидеть ID комментария по мы не сохраним его,
#         # хотя PostgreSQL имеет такие средства в своём арсенале, но пока не будем
#         # работать с сырыми SQL запросами, поэтому сформируем path после первого сохранения
#         # и пересохраним комментарий
#         try:
#             comment.path.extend(CommentV2.objects.get(id=form.cleaned_data['parent_comment']).path)
#             comment.path.append(comment.id)
#         except ObjectDoesNotExist:
#             comment.path.append(comment.id)
#
#         comment.save()
#
#     return redirect(news.get_absolute_url())

002.app_news.REG.PERM/mysite/app_news/templates/app_news/news_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Confirm delete news #{{ object.pk }}</title>
</head>
<body>
  <h1>Are you sure want to delete news #{{ object.pk }}?</h1>
  <br>
  <div>
    <a href="{% url 'app_news:news_details' pk=object.pk %}">Back to news</a>
  </div>
  <br>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Delete</button>
    </form>
  </div>
</body>
</html>

002.app_news.REG.PERM/mysite/app_news/templates/app_news/news_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>News #{{ news.pk }} details</title>
</head>
<body>
  <h1>News #{{ news.pk }} details</h1>
  <div>
      <h3>Title: {{ news.title }}</h3>
      <p>Content: {{ news.content }}</p>
      <p>News by - {{ news.publisher }}</p>
      <p>Date: {{ news.created_at }}</p>
  </div>
  <div>
    <a href="{% url 'app_news:news_update' pk=news.pk %}">Update news</a>
  </div>
  <div>
    <a href="{% url 'app_news:news_delete' pk=news.pk %}">Delete news</a>
  </div>
  <div>
    <a href="{% url 'app_news:news_list' %}">Back to news list</a>
  </div>

  <h2>Comments:</h2>
  <div>
      {% for comment in comments %}
          {% if comment.user %}
            <p><strong>Comment by {% firstof comment.user.first_name comment.user.username %}</strong></p>
          {% else %}
            <p><strong>Comment by anonim - {{ comment.name }}</strong></p>
          {% endif %}
          <p>Comment text: {{ comment.comment_text }}</p>
          <p>Date of created: {{ comment.created_at }}</p>
          ---------------------------------------
      {% endfor %}
  </div>
  <div>
      <h3>Create comment:</h3>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
      </form>
  </div>
</body>
</html>

002.app_news.REG.PERM/mysite/app_news/templates/app_news/news_detail_moder.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>News #{{ object.pk }} for modreation</title>
</head>
<body>
  <h1>News #{{ object.pk }} for moderation</h1>
<!--  <div>-->
<!--      <h3>Title: {{ object.title }}</h3>-->
<!--      <p>Content: {{ object.content }}</p>-->
<!--      <p>News by - {{ object.publisher }}</p>-->
<!--      <p>Date: {{ object.created_at }}</p>-->
<!--  </div>-->
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Update</button>
    </form>
  </div>
  <div>
    <a href="{% url 'app_news:news_delete' pk=news.pk %}">Delete news</a>
  </div>
  <div>
    <a href="{% url 'app_news:news_list_moder' %}">Back to news list for moderation</a>
  </div>
</body>
</html>

002.app_news.REG.PERM/mysite/app_news/templates/app_news/news_detail_v2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>News #{{ object.pk }} details</title>
</head>
<body>
  <h1>News #{{ object.pk }} details</h1>
  <div>
      <h3>Title: {{ object.title }}</h3>
      <p>Content: {{ object.content }}</p>
      <p>News by - {{ object.publisher }}</p>
      <p>Date: {{ object.created_at }}</p>
  </div>
  <div>
    <a href="{% url 'news_update' pk=news.pk %}">Update news</a>
  </div>
  <div>
    <a href="{% url 'news_delete' pk=news.pk %}">Delete news</a>
  </div>
  <div>
    <a href="{% url 'news_list' %}">Back to news list</a>
  </div>

  <h2>Comments:</h2>
  <div>
      {% for comment in comments %}
          {% if comment.user.username != 'guest' %}
            <p>Comment by {% firstof comment.user.first_name comment.user.username %}</p>
          {% else %}
            <p>Comment by guest(anonim) - {{ comment.name }}</p>
          {% endif %}
          <p>Comment text: {{ comment.comment_text }}</p>
          <p>Date of created: {{ comment.created_at }}</p>
      {% endfor %}
  </div>
  <div>
      <h3>Create comment:</h3>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
      </form>
  </div>


    <h2>Комментарии</h2>
    {% for comment in comments %}
        <a name="comment-{{ comment.id }}"></a>
        <div class="row" id="{{ comment.id }}">
            <div class="col-md-{{ comment.get_col }} col-md-offset-{{ comment.get_offset }}">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <strong>{{ comment.author_id.get_full_name|default:comment.author_id.username }}</strong>&nbsp;&nbsp;
                        {{ comment.pub_date }}
                        <a href="#comment-{{ comment.id }}">#</a>
                    </div>
                    <div class="panel-body">
                        <div>{{ comment.content|safe }}</div>
                        {% if form %}<a class="btn btn-default btn-xs pull-right"
                                        onclick="return show_comments_form({{ comment.id }})">
                            {% bootstrap_icon "share-alt" %}&nbsp;&nbsp;Ответить</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    {% if form %}
        <h3 id="write_comment"><a onclick="return show_comments_form('write_comment')">Написать комментарий</a></h3>
        <form id="comment_form" action="{% url 'app_news:add_comment' article.id %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">{% bootstrap_icon "comment" %}&nbsp;&nbsp;Комментировать</button>
        {% endbuttons %}
        </form>
    {% else %}
        <div class="panel panel-warning">
            <div class="panel-heading">
                <h3 class="panel-title">Комментарии</h3>
            </div>
            <div class="panel-body">
                Только авторизованные пользователи могут оставлять комментарии.<br />
            </div>
        </div>
    {% endif %}

</body>
</html>

002.app_news.REG.PERM/mysite/app_news/templates/app_news/news_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create news</title>
</head>
<body>
  <h1>Create news</h1>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Create</button>
    </form>
  </div>
  <div>
    <a href="{% url 'app_news:news_list' %}">Back to news list</a>
  </div>
</body>
</html>

002.app_news.REG.PERM/mysite/app_news/templates/app_news/news_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Новости</title>
</head>
<body>
    <h1>Новости</h1>
    {% if news_list %}
    <div>
        <div>
            <h3>Filter for news list:</h3>
            <form method="post">
                {% csrf_token %}
                <select name="format">
                    <option value="Filter" disabled selected>Filter</option>
                    <option value="title">Title (ascending)</option>
                    <option value="-title">Title (descending)</option>
                    <option value="author">Author (ascending)</option>
                    <option value="-author">Author (descending)</option>
                    <option value="created_at">Date (ascending)</option>
                    <option value="-created_at">Date (descending)</option>
                </select>
                <button type="submit">Filter</button>
            </form>
        </div>

        {% for news in news_list %}
            {% if news.is_active %}
                <div>
                  <h3><a href="{% url 'app_news:news_details' pk=news.pk %}">Title: {{ news.title }}</a></h3>
                  <p>Content: {{ news.content }}</p>
                  <p>Author: {{ news.author }}</p>
                  <p>Date: {{ news.created_at }}</p>
                </div>
            {% endif %}
        {% endfor %}
    </div>

    {% else %}
        <p>Новостей нет.</p>
    {% endif %}

    <div>
        <a href="{% url 'app_news:news_create' %}">Create news (only verify)</a>
    </div>

    <br>
    <div>
    <a href="{% url 'main' %}">Back to main</a>
    </div>
</body>
</html>

002.app_news.REG.PERM/mysite/app_news/templates/app_news/news_list_moder.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Новости на модерацию</title>
</head>
<body>
    <h1>Новости на модерацию</h1>
    {% if news_list %}
    <div>
        {% for news in news_list %}
            {% if not news.is_active %}
                <div>
                  <h3><a href="{% url 'app_news:news_details_moder' pk=news.pk %}">Title: {{ news.title }}</a></h3>
                  <p>Content: {{ news.content }}</p>
                </div>
            {% endif %}
        {% endfor %}
    </div>

    {% else %}
        <p>Новостей нет.</p>
    {% endif %}

<!--    <div>-->
<!--        <a href="{% url 'app_news:news_create' %}">Create news (only verify)</a>-->
<!--    </div>-->

    <br>
    <div>
    <a href="{% url 'main' %}">Back to main</a>
    </div>
</body>
</html>

002.app_news.REG.PERM/mysite/app_news/templates/app_news/news_update_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Update news</title>
</head>
<body>
    <h1>Update news</h1>
    <div>
        <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit">Update</button>
        </form>
    </div>
    <div>
    <a href="{% url 'app_news:news_details' pk=object.pk %}">Back to news</a>
    </div>
</body>
</html>